### ISSUE TITLE
table layout needs to be fixed

### ISSUE THREAD

**Issue by bgruening** [mulled/mulled#2]
```
 We can make this file beautiful and searchable if this error is corrected: Illegal quoting in line 2. 
```

**Comment by thriqon** [comment]
I just sent a message to Github, this is not an invalid TSV file. Quotes are nothing special in TSV (different from CSV). Keeping this open for reference.

**Comment by thriqon** [comment]
Github answered:

> [..]
> I believe the TSV data should render correctly with the quotes if you first surround the entire field in quotes, and then use doubled-up quotes inside that for the quoted material. 
> 
> For example:
> 
> "C ""ASD"""
> 
> Give that a try, and let us know if you're still having trouble.

I answered, that this is
- non-standard
- more complicated to parse (see above)
- pretty bad for shell script snippets
- probably caused due to their usage of a CSV parser for TSV content

Unfortunately, I have no idea whether they will implement correct behavior or if we have to fall back to CSV semantics.

**Comment by thriqon** [comment]
Github answered:

> [..]
> Yep, you're right, we are using a CSV parser with a different delimiter. I can see how that would be frustrating in cases like this, and I'll definitely pass that on to the team to look into, but I can't promise if or when that might change in the future. [..]

Putting this on hold, as far as I can see we have to live with this for now :disappointed:
